# PIN Tool Configuration Makefile
# For pre-compiled PIN Kit

PINKIT ?= $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/../../../

# Detect OS and Architecture
ifeq ($(OS),Windows_NT)
    OS_TYPE := nt
    HOST_OS := windows
    ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
        TARGET ?= intel64
    else
        ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
            TARGET ?= intel64
        else
            TARGET ?= ia32
        endif
    endif
else
    OS_TYPE := unix
    HOST_OS := linux
    UNAME_M := $(shell uname -m)
    ifeq ($(UNAME_M),x86_64)
        TARGET ?= intel64
    else
        TARGET ?= ia32
    endif
endif

# Compiler setup for Windows with clang-cl
ifeq ($(OS_TYPE),nt)
    TOOL_CXX ?= clang-cl
    TOOL_CC ?= clang-cl
    TOOL_AS ?= as
    TOOL_LD ?= lld-link
    TOOL_AR ?= llvm-lib
    OBJSUFFIX := .obj
    PINTOOL_SUFFIX := .dll
    EXESUFFIX := .exe
    SOSUFFIX := .dll
    DLL_PREFIX := 
    AR_SUFFIX := .lib
else
    TOOL_CXX ?= g++
    TOOL_CC ?= gcc
    TOOL_AS ?= as
    TOOL_LD ?= g++
    TOOL_AR ?= ar
    OBJSUFFIX := .o
    PINTOOL_SUFFIX := .so
    EXESUFFIX := 
    SOSUFFIX := .so
    DLL_PREFIX := lib
    AR_SUFFIX := .a
endif

# PIN Directories
PIN_LIBDIR := $(PINKIT)/$(TARGET)/lib
PIN_INCLUDE := $(PINKIT)/source/include
TOOLS_ROOT := $(PINKIT)

# Output directories
OBJDIR ?= obj-$(TARGET)
OUTDIR := .

# Default flags
TOOL_CPPFLAGS ?= -DPIN_CRT=1 -D_GNU_SOURCE
TOOL_CXXFLAGS ?= -std=c++17 -fPIC -O2 -Wall -Werror
TOOL_LDFLAGS ?= -shared

ifeq ($(TARGET),ia32)
    TOOL_CXXFLAGS += -m32
    TOOL_LDFLAGS += -m32
else
    TOOL_CXXFLAGS += -m64
    TOOL_LDFLAGS += -m64
endif

# Build rules
%.o: %.cpp
	$(TOOL_CXX) $(TOOL_CPPFLAGS) $(TOOL_CXXFLAGS) -I$(PIN_INCLUDE) -c $< -o $@

.PHONY: all clean
